# Generated by Django 5.1 on 2024-09-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_shortenedurl_long_code_alter_shortenedurl_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='long_code',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
